// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AllMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from AllMsg.proto</summary>
public static partial class AllMsgReflection {

  #region Descriptor
  /// <summary>File descriptor for AllMsg.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AllMsgReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxBbGxNc2cucHJvdG8aC0xvZ2luLnByb3RvIq4BCgZOZXRNc2cSDAoEY29k",
          "ZRgBIAEoCRIhCghsb2dpblJlcRgCIAEoCzINLkNTX0xvZ2luX1JlcUgAEiEK",
          "CGxvZ2luUmVzGAMgASgLMg0uU0NfTG9naW5fUmVzSAASIwoJbG9nb3V0UmVx",
          "GAQgASgLMg4uQ1NfTG9nb3V0X1JlcUgAEiMKCWxvZ291dFJlcxgFIAEoCzIO",
          "LlNDX0xvZ291dF9SZXNIAEIGCgRkYXRhYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::LoginReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::NetMsg), global::NetMsg.Parser, new[]{ "Code", "LoginReq", "LoginRes", "LogoutReq", "LogoutRes" }, new[]{ "Data" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class NetMsg : pb::IMessage<NetMsg> {
  private static readonly pb::MessageParser<NetMsg> _parser = new pb::MessageParser<NetMsg>(() => new NetMsg());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<NetMsg> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AllMsgReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NetMsg() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NetMsg(NetMsg other) : this() {
    code_ = other.code_;
    switch (other.DataCase) {
      case DataOneofCase.LoginReq:
        LoginReq = other.LoginReq.Clone();
        break;
      case DataOneofCase.LoginRes:
        LoginRes = other.LoginRes.Clone();
        break;
      case DataOneofCase.LogoutReq:
        LogoutReq = other.LogoutReq.Clone();
        break;
      case DataOneofCase.LogoutRes:
        LogoutRes = other.LogoutRes.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public NetMsg Clone() {
    return new NetMsg(this);
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 1;
  private string code_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Code {
    get { return code_; }
    set {
      code_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "loginReq" field.</summary>
  public const int LoginReqFieldNumber = 2;
  /// <summary>
  ///登录 | 登出
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::CS_Login_Req LoginReq {
    get { return dataCase_ == DataOneofCase.LoginReq ? (global::CS_Login_Req) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.LoginReq;
    }
  }

  /// <summary>Field number for the "loginRes" field.</summary>
  public const int LoginResFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::SC_Login_Res LoginRes {
    get { return dataCase_ == DataOneofCase.LoginRes ? (global::SC_Login_Res) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.LoginRes;
    }
  }

  /// <summary>Field number for the "logoutReq" field.</summary>
  public const int LogoutReqFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::CS_Logout_Req LogoutReq {
    get { return dataCase_ == DataOneofCase.LogoutReq ? (global::CS_Logout_Req) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.LogoutReq;
    }
  }

  /// <summary>Field number for the "logoutRes" field.</summary>
  public const int LogoutResFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::SC_Logout_Res LogoutRes {
    get { return dataCase_ == DataOneofCase.LogoutRes ? (global::SC_Logout_Res) data_ : null; }
    set {
      data_ = value;
      dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.LogoutRes;
    }
  }

  private object data_;
  /// <summary>Enum of possible cases for the "data" oneof.</summary>
  public enum DataOneofCase {
    None = 0,
    LoginReq = 2,
    LoginRes = 3,
    LogoutReq = 4,
    LogoutRes = 5,
  }
  private DataOneofCase dataCase_ = DataOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DataOneofCase DataCase {
    get { return dataCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void ClearData() {
    dataCase_ = DataOneofCase.None;
    data_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as NetMsg);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(NetMsg other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Code != other.Code) return false;
    if (!object.Equals(LoginReq, other.LoginReq)) return false;
    if (!object.Equals(LoginRes, other.LoginRes)) return false;
    if (!object.Equals(LogoutReq, other.LogoutReq)) return false;
    if (!object.Equals(LogoutRes, other.LogoutRes)) return false;
    if (DataCase != other.DataCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Code.Length != 0) hash ^= Code.GetHashCode();
    if (dataCase_ == DataOneofCase.LoginReq) hash ^= LoginReq.GetHashCode();
    if (dataCase_ == DataOneofCase.LoginRes) hash ^= LoginRes.GetHashCode();
    if (dataCase_ == DataOneofCase.LogoutReq) hash ^= LogoutReq.GetHashCode();
    if (dataCase_ == DataOneofCase.LogoutRes) hash ^= LogoutRes.GetHashCode();
    hash ^= (int) dataCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Code.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Code);
    }
    if (dataCase_ == DataOneofCase.LoginReq) {
      output.WriteRawTag(18);
      output.WriteMessage(LoginReq);
    }
    if (dataCase_ == DataOneofCase.LoginRes) {
      output.WriteRawTag(26);
      output.WriteMessage(LoginRes);
    }
    if (dataCase_ == DataOneofCase.LogoutReq) {
      output.WriteRawTag(34);
      output.WriteMessage(LogoutReq);
    }
    if (dataCase_ == DataOneofCase.LogoutRes) {
      output.WriteRawTag(42);
      output.WriteMessage(LogoutRes);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Code.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Code);
    }
    if (dataCase_ == DataOneofCase.LoginReq) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LoginReq);
    }
    if (dataCase_ == DataOneofCase.LoginRes) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LoginRes);
    }
    if (dataCase_ == DataOneofCase.LogoutReq) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LogoutReq);
    }
    if (dataCase_ == DataOneofCase.LogoutRes) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LogoutRes);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(NetMsg other) {
    if (other == null) {
      return;
    }
    if (other.Code.Length != 0) {
      Code = other.Code;
    }
    switch (other.DataCase) {
      case DataOneofCase.LoginReq:
        if (LoginReq == null) {
          LoginReq = new global::CS_Login_Req();
        }
        LoginReq.MergeFrom(other.LoginReq);
        break;
      case DataOneofCase.LoginRes:
        if (LoginRes == null) {
          LoginRes = new global::SC_Login_Res();
        }
        LoginRes.MergeFrom(other.LoginRes);
        break;
      case DataOneofCase.LogoutReq:
        if (LogoutReq == null) {
          LogoutReq = new global::CS_Logout_Req();
        }
        LogoutReq.MergeFrom(other.LogoutReq);
        break;
      case DataOneofCase.LogoutRes:
        if (LogoutRes == null) {
          LogoutRes = new global::SC_Logout_Res();
        }
        LogoutRes.MergeFrom(other.LogoutRes);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Code = input.ReadString();
          break;
        }
        case 18: {
          global::CS_Login_Req subBuilder = new global::CS_Login_Req();
          if (dataCase_ == DataOneofCase.LoginReq) {
            subBuilder.MergeFrom(LoginReq);
          }
          input.ReadMessage(subBuilder);
          LoginReq = subBuilder;
          break;
        }
        case 26: {
          global::SC_Login_Res subBuilder = new global::SC_Login_Res();
          if (dataCase_ == DataOneofCase.LoginRes) {
            subBuilder.MergeFrom(LoginRes);
          }
          input.ReadMessage(subBuilder);
          LoginRes = subBuilder;
          break;
        }
        case 34: {
          global::CS_Logout_Req subBuilder = new global::CS_Logout_Req();
          if (dataCase_ == DataOneofCase.LogoutReq) {
            subBuilder.MergeFrom(LogoutReq);
          }
          input.ReadMessage(subBuilder);
          LogoutReq = subBuilder;
          break;
        }
        case 42: {
          global::SC_Logout_Res subBuilder = new global::SC_Logout_Res();
          if (dataCase_ == DataOneofCase.LogoutRes) {
            subBuilder.MergeFrom(LogoutRes);
          }
          input.ReadMessage(subBuilder);
          LogoutRes = subBuilder;
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
